spring.application.name=g3
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

resilience4j.timelimiter.instances.idv.timeoutDuration=65s
resilience4j.retry.instances.idv.maxAttempts=3
resilience4j.retry.instances.idv.waitDuration=2s
resilience4j.retry.instances.idv.retryExceptions=com.example.g3.client.IdvRetryableException
resilience4j.circuitbreaker.instances.idv.slidingWindowSize=10
resilience4j.circuitbreaker.instances.idv.failureRateThreshold=50
resilience4j.circuitbreaker.instances.idv.waitDurationInOpenState=10s

resilience4j.retry.instances.cis.maxAttempts=3
resilience4j.retry.instances.cis.waitDuration=2s
resilience4j.retry.instances.cis.retryExceptions=com.example.g3.client.CisRetryableException
resilience4j.circuitbreaker.instances.cis.slidingWindowSize=10
resilience4j.circuitbreaker.instances.cis.failureRateThreshold=50
resilience4j.circuitbreaker.instances.cis.waitDurationInOpenState=10s

resilience4j.retry.instances.document.maxAttempts=3
resilience4j.retry.instances.document.waitDuration=2s
resilience4j.retry.instances.document.retryExceptions=com.example.g3.client.DocumentRetryableException
resilience4j.circuitbreaker.instances.document.slidingWindowSize=10
resilience4j.circuitbreaker.instances.document.failureRateThreshold=50
resilience4j.circuitbreaker.instances.document.waitDurationInOpenState=10s
resilience4j.timelimiter.instances.document.timeoutDuration=3s

resilience4j.retry.instances.risk.maxAttempts=3
resilience4j.retry.instances.risk.waitDuration=5s
resilience4j.retry.instances.risk.retryExceptions=com.example.g3.client.RiskRetryableException
resilience4j.circuitbreaker.instances.risk.slidingWindowSize=10
resilience4j.circuitbreaker.instances.risk.failureRateThreshold=50
resilience4j.circuitbreaker.instances.risk.waitDurationInOpenState=10s
resilience4j.timelimiter.instances.risk.timeoutDuration=65s
