spring:
  application:
    name: onboarding-orchestrator

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/orchestrator_db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update # Automatically creates the tables for development
    show-sql: true

  # Kafka Configuration
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: onboarding-orchestrator-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        schema.registry.url: http://localhost:8081
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

idv.service.url: http://localhost:8089
document.service.url: http://localhost:8089
risk.service.url: http://localhost:8089
cis.service.url: http://localhost:8089

# Resilience4j Configuration
resilience4j.circuitbreaker:
  instances:
    downstream-services:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      waitDurationInOpenState: 10s
      failureRateThreshold: 50


resilience4j.timelimiter:
  instances:
    idv:
      timeoutDuration: 65s
    document:
      timeoutDuration: 3s
    risk:
      timeoutDuration: 65s
      
resilience4j.retry:
  instances:
    idv:
      maxAttempts: 3
      waitDuration: 2s
      retryExceptions: com.example.g3.client.IdvRetryableException
    cis:
      maxAttempts: 3
      waitDuration: 2s
      retryExceptions: com.example.g3.client.CisRetryableException
    document:
      maxAttempts: 3
      waitDuration: 2s
      retryExceptions: com.example.g3.client.DocumentRetryableException
    risk:
      maxAttempts: 3
      waitDuration: 5s
      retryExceptions: com.example.g3.client.RiskRetryableException
  
# Logging for Promtail
logging:
  file:
    name: logs/orchestrator.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"